stages:
  - build
  - deploy

build:
  image: docker:cli
  services:
    - name: docker:dind
      command:
        - --insecure-registry=registry:5000
  variables:
    DOCKER_TLS_CERTDIR: ""
  stage: build
  script:
    - docker build --tag ${MYAPP_FULL_PATH} ./app
    - docker push ${MYAPP_FULL_PATH}

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."