stages:
  - build
  - deploy

variables:
  LOCAL_DOCKER_REGISTRY: "registry:5000"
  MYAPP_IMAGE: "myapp"
  MYAPP_IMAGE_TAG: "v0.1.0-ci"
  MYAPP_FULL_PATH: "$LOCAL_DOCKER_REGISTRY/$MYAPP_IMAGE:$MYAPP_IMAGE_TAG"

build:
  image: docker:cli
  services:
    - name: docker:dind
      command:
        - --insecure-registry=registry:5000
  variables:
    DOCKER_TLS_CERTDIR: ""
  stage: build
  script:
    - docker build --tag ${MYAPP_FULL_PATH} ./app
    - docker push ${MYAPP_FULL_PATH}

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."