apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}-deployment

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          
          ports:
            - containerPort: {{ .Values.image.containerPort }}

          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}