apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}-service
spec:
  selector: 
    app: {{ .Release.Name }}-{{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}